
DEBUG_LOG_ENABLED = $CONFIG_DEBUG_LOG_ENABLED

WIFI_ESSID = '$CONFIG_WIFI_ESSID'
WIFI_PASSWD = '$CONFIG_WIFI_PASSWD'

CARBON_HOST = '$CONFIG_CARBON_HOST'
CARBON_PORT = $CONFIG_CARBON_PORT
CARBON_DATA_PATH_PREFIX = '$CONFIG_CARBON_DATA_PATH_PREFIX'

NTP_REFRESH_EACH_N_ITERATIONS = 19
ENTRIES_MEASURE_BATCH_SIZE = 3
ENTRIES_SEND_BATCH_SIZE = ENTRIES_MEASURE_BATCH_SIZE * 3
SECONDS_BETWEEN_MEASUREMENTS = 10

# Max is about 3:30h https://thingpulse.com/max-deep-sleep-for-esp8266/
DEEPSLEEP_SECONDS = 15

ERROR_TIMEOUT_HOLDOFF_MAX_SECONDS = 60

STATE_MAX_ENTRIES = 60
DELETE_OLDER_ELEMENTS_COUNT_IF_MAX_REACHED = 30
STORAGE_FILENAME = 'db.dat'

DHT22_PIN = 12
TEMP_SENSOR_PIN = 13

